export interface FullCustomerProfile {
  id: string;
  firstName: string;
  lastName: string;
  gender: "Male" | "Female";
  dateOfBirth: string;
  country: string;
  address: string;
  height: number;
  email: string;
  phone: string;
  college: string;
  degree: string;
  income: number;
  employmentType: "Government" | "Private";
  company: string; // NA if Government
  designation: string;
  maritalStatus: "Never Married" | "Divorced";
  languages: string[];
  hobbies: string[];
  siblings: number;
  caste: string;
  religion:
    | "Hindu"
    | "Muslim"
    | "Sikh"
    | "Christian"
    | "Buddhist"
    | "Jain"
    | "Parsi (Zoroastrian)"
    | "Other"
    | "No Religion / Atheist"
    | "Spiritual (but not religious)";
  wantKids: "Yes" | "No" | "Maybe";
  openToRelocate: "Yes" | "No" | "Maybe";
  openToPets: "Yes" | "No" | "Maybe";
  accountStatus: "new" | "active" | "matched" | "paused";
  avatar?: string;
  joinDate: string;
  lastActivity: string; // it's a date
  bio: string;
  familySize: number;
  importanceOfCasteOfThePartner: "HIGH" | "MEDIUM" | "LOW";
  importanceOfReligionOfThePartner: "HIGH" | "MEDIUM" | "LOW";
}

export const dummyProfiles: FullCustomerProfile[] = [
  // Current customers (existing profiles)
  {
    id: "1",
    firstName: "Priya",
    lastName: "Sharma",
    gender: "Female",
    dateOfBirth: "1996-03-15",
    country: "India",
    address: "Mumbai",
    height: 163, // cm (approx 5'4")
    email: "priya.sharma@email.com",
    phone: "+91 98765 43210",
    college: "University of Mumbai",
    degree: "MBA in Marketing",
    income: 1200000, // INR per annum
    employmentType: "Private",
    company: "Tata Consultancy Services",
    designation: "Marketing Manager",
    maritalStatus: "Never Married",
    languages: ["Hindi", "English", "Marathi"],
    hobbies: ["Traveling", "Cooking", "Photography"],
    siblings: 1,
    caste: "Brahmin",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "Yes",
    accountStatus: "active",
    avatar: undefined,
    joinDate: "2024-01-15",
    lastActivity: "2024-01-20",
    bio: "I'm a passionate marketing professional who loves traveling and exploring new cultures. Looking for a life partner who shares similar values and interests.",
    familySize: 4, // parents + self + 1 sibling
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "2",
    firstName: "Rahul",
    lastName: "Gupta",
    gender: "Male",
    dateOfBirth: "1992-07-22",
    country: "India",
    address: "Delhi",
    height: 178, // cm (approx 5'10")
    email: "rahul.gupta@email.com",
    phone: "+91 98765 43211",
    college: "Indian Institute of Technology Delhi",
    degree: "B.Tech in Computer Science",
    income: 1800000,
    employmentType: "Private",
    company: "Google India",
    designation: "Software Engineer",
    maritalStatus: "Never Married",
    languages: ["Hindi", "English", "Punjabi"],
    hobbies: ["Coding", "Fitness", "Cricket"],
    siblings: 0,
    caste: "Agarwal",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "No",
    accountStatus: "new",
    avatar: undefined,
    joinDate: "2024-01-18",
    lastActivity: "2024-01-18",
    bio: "Tech enthusiast and fitness lover. I enjoy coding, playing cricket, and spending time with family. Seeking a caring and understanding partner.",
    familySize: 3, // parents + self
    importanceOfCasteOfThePartner: "LOW",
    importanceOfReligionOfThePartner: "MEDIUM",
  },
  {
    id: "3",
    firstName: "Anita",
    lastName: "Patel",
    gender: "Female",
    dateOfBirth: "1995-11-08",
    country: "India",
    address: "Bangalore",
    height: 160, // cm (approx 5'3")
    email: "anita.patel@email.com",
    phone: "+91 98765 43212",
    college: "National Institute of Design",
    degree: "M.Des in Product Design",
    income: 1000000,
    employmentType: "Private",
    company: "Flipkart",
    designation: "Senior UX Designer",
    maritalStatus: "Divorced",
    languages: ["Hindi", "English", "Gujarati"],
    hobbies: ["Art", "Music", "Sketching"],
    siblings: 2,
    caste: "Patel",
    religion: "Hindu",
    wantKids: "Maybe",
    openToRelocate: "No",
    openToPets: "Yes",
    accountStatus: "matched",
    avatar: undefined,
    joinDate: "2024-01-10",
    lastActivity: "2024-01-19",
    bio: "Creative designer with a passion for user experience and innovation. I love art, music, and meaningful conversations.",
    familySize: 5, // parents + self + 2 siblings
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "HIGH",
  },

  // Additional dummy profiles for matching pool
  {
    id: "101",
    firstName: "Arjun",
    lastName: "Singh",
    gender: "Male",
    dateOfBirth: "1990-05-12",
    country: "India",
    address: "Mumbai",
    height: 183, // cm (6'0")
    email: "arjun.singh@email.com",
    phone: "+91 98765 43213",
    college: "Indian Institute of Management Ahmedabad",
    degree: "MBA in Finance",
    income: 2500000,
    employmentType: "Private",
    company: "Goldman Sachs",
    designation: "Investment Banker",
    maritalStatus: "Never Married",
    languages: ["Hindi", "English", "Punjabi"],
    hobbies: ["Adventure Sports", "Travel", "Reading"],
    siblings: 1,
    caste: "Rajput",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "Maybe",
    accountStatus: "active",
    avatar: undefined,
    joinDate: "2024-01-12",
    lastActivity: "2024-01-21",
    bio: "Finance professional with a passion for adventure sports and travel. Looking for an intelligent and ambitious partner.",
    familySize: 4,
    importanceOfCasteOfThePartner: "HIGH",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "102",
    firstName: "Kavya",
    lastName: "Reddy",
    gender: "Female",
    dateOfBirth: "1994-09-18",
    country: "India",
    address: "Hyderabad",
    height: 165, // cm (5'5")
    email: "kavya.reddy@email.com",
    phone: "+91 98765 43214",
    college: "Indian Institute of Science",
    degree: "PhD in Biotechnology",
    income: 1500000,
    employmentType: "Private",
    company: "Biocon",
    designation: "Research Scientist",
    maritalStatus: "Never Married",
    languages: ["Telugu", "Hindi", "English"],
    hobbies: ["Reading", "Classical Music", "Gardening"],
    siblings: 0,
    caste: "Reddy",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "Yes",
    accountStatus: "active",
    avatar: undefined,
    joinDate: "2024-01-14",
    lastActivity: "2024-01-20",
    bio: "Research scientist passionate about biotechnology and making a difference in healthcare. Love reading and classical music.",
    familySize: 3,
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "103",
    firstName: "Vikram",
    lastName: "Mehta",
    gender: "Male",
    dateOfBirth: "1988-12-03",
    country: "India",
    address: "Bangalore",
    height: 180, // cm (approx 5'11")
    email: "vikram.mehta@email.com",
    phone: "+91 98765 43215",
    college: "Indian Institute of Technology Bombay",
    degree: "B.Tech in Mechanical Engineering",
    income: 2200000,
    employmentType: "Private",
    company: "Tesla",
    designation: "Senior Engineer",
    maritalStatus: "Never Married",
    languages: ["Hindi", "English", "Gujarati"],
    hobbies: ["Hiking", "Photography", "Cooking"],
    siblings: 2,
    caste: "Brahmin",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "No",
    accountStatus: "active",
    avatar: undefined,
    joinDate: "2024-01-16",
    lastActivity: "2024-01-19",
    bio: "Mechanical engineer working on sustainable transportation. Enjoy hiking, photography, and spending time with family.",
    familySize: 5,
    importanceOfCasteOfThePartner: "HIGH",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "104",
    firstName: "Sneha",
    lastName: "Joshi",
    gender: "Female",
    dateOfBirth: "1993-07-25",
    country: "India",
    address: "Pune",
    height: 157, // cm (approx 5'2")
    email: "sneha.joshi@email.com",
    phone: "+91 98765 43216",
    college: "Symbiosis Institute of Design",
    degree: "M.Des in Fashion Design",
    income: 800000,
    employmentType: "Private",
    company: "Fabindia",
    designation: "Fashion Designer",
    maritalStatus: "Never Married",
    languages: ["Hindi", "English", "Marathi"],
    hobbies: ["Yoga", "Sustainable Fashion", "Sketching"],
    siblings: 1,
    caste: "Brahmin",
    religion: "Hindu",
    wantKids: "Maybe",
    openToRelocate: "No",
    openToPets: "Yes",
    accountStatus: "new",
    avatar: undefined,
    joinDate: "2024-01-17",
    lastActivity: "2024-01-17",
    bio: "Fashion designer with a love for traditional Indian textiles and sustainable fashion. Enjoy yoga and meditation.",
    familySize: 4,
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "MEDIUM",
  },
  {
    id: "105",
    firstName: "Karan",
    lastName: "Agarwal",
    gender: "Male",
    dateOfBirth: "1991-04-14",
    country: "India",
    address: "Delhi",
    height: 175, // cm (approx 5'9")
    email: "karan.agarwal@email.com",
    phone: "+91 98765 43217",
    college: "Delhi School of Economics",
    degree: "MA in Economics",
    income: 1600000,
    employmentType: "Private",
    company: "McKinsey & Company",
    designation: "Business Analyst",
    maritalStatus: "Never Married",
    languages: ["Hindi", "English"],
    hobbies: ["Chess", "Reading", "Strategy Games"],
    siblings: 1,
    caste: "Agarwal",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "Maybe",
    accountStatus: "active",
    avatar: undefined,
    joinDate: "2024-01-13",
    lastActivity: "2024-01-21",
    bio: "Business analyst with a passion for strategy and problem-solving. Love playing chess and reading business books.",
    familySize: 4,
    importanceOfCasteOfThePartner: "LOW",
    importanceOfReligionOfThePartner: "MEDIUM",
  },
  {
    id: "106",
    firstName: "Meera",
    lastName: "Nair",
    gender: "Female",
    dateOfBirth: "1989-11-30",
    country: "India",
    address: "Kochi",
    height: 163, // cm (approx 5'4")
    email: "meera.nair@email.com",
    phone: "+91 98765 43218",
    college: "All India Institute of Medical Sciences",
    degree: "MBBS, MD in Pediatrics",
    income: 2000000,
    employmentType: "Private",
    company: "Apollo Hospitals",
    designation: "Pediatrician",
    maritalStatus: "Never Married",
    languages: ["Malayalam", "Hindi", "English"],
    hobbies: ["Classical Dance", "Cooking", "Volunteering"],
    siblings: 1,
    caste: "Nair",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "Yes",
    accountStatus: "active",
    avatar: undefined,
    joinDate: "2024-01-11",
    lastActivity: "2024-01-20",
    bio: "Pediatrician dedicated to child healthcare. Love classical dance, cooking, and spending time with children.",
    familySize: 4,
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "107",
    firstName: "Rohit",
    lastName: "Kapoor",
    gender: "Male",
    dateOfBirth: "1987-08-22",
    country: "India",
    address: "Chennai",
    height: 173, // cm (approx 5'8")
    email: "rohit.kapoor@email.com",
    phone: "+91 98765 43219",
    college: "Indian Institute of Management Bangalore",
    degree: "MBA in Operations",
    income: 1900000,
    employmentType: "Private",
    company: "Amazon",
    designation: "Operations Manager",
    maritalStatus: "Divorced",
    languages: ["Hindi", "English", "Tamil"],
    hobbies: ["Cricket", "Movies", "Culinary Experiments"],
    siblings: 0,
    caste: "Kapoor",
    religion: "Hindu",
    wantKids: "Maybe",
    openToRelocate: "Yes",
    openToPets: "No",
    accountStatus: "active",
    avatar: undefined,
    joinDate: "2024-01-15",
    lastActivity: "2024-01-18",
    bio: "Operations manager with experience in e-commerce logistics. Enjoy cricket, movies, and exploring new cuisines.",
    familySize: 3,
    importanceOfCasteOfThePartner: "LOW",
    importanceOfReligionOfThePartner: "MEDIUM",
  },
  {
    id: "108",
    firstName: "Divya",
    lastName: "Iyer",
    gender: "Female",
    dateOfBirth: "1992-02-14",
    country: "India",
    address: "Bangalore",
    height: 160, // cm (approx 5'3")
    email: "divya.iyer@email.com",
    phone: "+91 98765 43220",
    college: "Indian Institute of Technology Madras",
    degree: "B.Tech in Electronics",
    income: 1400000,
    employmentType: "Private",
    company: "Intel",
    designation: "Hardware Engineer",
    maritalStatus: "Never Married",
    languages: ["Tamil", "Hindi", "English"],
    hobbies: ["Carnatic Music", "Reading", "Electronics DIY"],
    siblings: 2,
    caste: "Iyer",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "Yes",
    accountStatus: "new",
    avatar: undefined,
    joinDate: "2024-01-19",
    lastActivity: "2024-01-19",
    bio: "Hardware engineer passionate about technology and innovation. Love carnatic music, reading, and temple visits.",
    familySize: 5,
    importanceOfCasteOfThePartner: "HIGH",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "109",
    firstName: "Amit",
    lastName: "Verma",
    gender: "Male",
    dateOfBirth: "1990-10-05",
    country: "India",
    address: "Gurgaon",
    height: 185, // cm (approx 6'1")
    email: "amit.verma@email.com",
    phone: "+91 98765 43221",
    college: "Indian School of Business",
    degree: "MBA in Marketing",
    income: 2100000,
    employmentType: "Private",
    company: "Unilever",
    designation: "Brand Manager",
    maritalStatus: "Never Married",
    languages: ["Hindi", "English"],
    hobbies: ["Fitness", "Travel", "Entrepreneurship"],
    siblings: 1,
    caste: "Brahmin",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "Maybe",
    accountStatus: "active",
    avatar: undefined,
    joinDate: "2024-01-10",
    lastActivity: "2024-01-21",
    bio: "Brand manager with expertise in consumer goods marketing. Passionate about fitness, travel, and entrepreneurship.",
    familySize: 4,
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "MEDIUM",
  },
  {
    id: "110",
    firstName: "Riya",
    lastName: "Bansal",
    gender: "Female",
    dateOfBirth: "1995-06-08",
    country: "India",
    address: "Jaipur",
    height: 165, // cm (approx 5'5")
    email: "riya.bansal@email.com",
    phone: "+91 98765 43222",
    college: "Lady Shri Ram College",
    degree: "BA in Psychology",
    income: 900000,
    employmentType: "Private",
    company: "Teach for India",
    designation: "Program Manager",
    maritalStatus: "Never Married",
    languages: ["Hindi", "English", "Rajasthani"],
    hobbies: ["Painting", "Classical Dance", "Social Work"],
    siblings: 0,
    caste: "Bansal",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "Yes",
    accountStatus: "active",
    avatar: undefined,
    joinDate: "2024-01-16",
    lastActivity: "2024-01-20",
    bio: "Program manager working in education sector. Passionate about social impact, painting, and classical dance.",
    familySize: 3,
    importanceOfCasteOfThePartner: "LOW",
    importanceOfReligionOfThePartner: "HIGH",
  },
];

export const getCustomerProfiles = (): FullCustomerProfile[] => {
  return dummyProfiles;
};

export const getMatchingPool = (
  excludeIds: string[] = [],
): FullCustomerProfile[] => {
  return dummyProfiles.filter((profile) => !excludeIds.includes(profile.id));
};

export const getProfileById = (id: string): FullCustomerProfile | undefined => {
  return dummyProfiles.find((profile) => profile.id === id);
};

export const getDummyProfiles = (): FullCustomerProfile[] => {
  return dummyProfiles;
};
