import type { PrismaClient } from "@prisma/client";

// Dummy profiles data
const dummyProfiles = [
  {
    id: "422",
    firstName: "Suresh",
    lastName: "Reddy",
    gender: "Male",
    dateOfBirth: "1991-03-08",
    country: "India",
    city: "Bangalore",
    height: "175",
    email: "suresh.reddy@email.com",
    phone: "9876543277",
    college: "RV College of Engineering",
    degree: "B.E. in Civil Engineering",
    income: "1500000",
    employmentType: "Private",
    company: "L&T Construction",
    designation: "Project Engineer",
    maritalStatus: "NeverMarried",
    languages: "Telugu, Kannada, English",
    hobbies: "Construction Management, Fitness, Photography",
    siblings: "1",
    caste: "Reddy",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "No",
    bio: "Diligent project engineer passionate about overseeing large-scale construction projects from conception to completion. I prioritize physical fitness and enjoy capturing the progress of my work through photography. Seeking a disciplined and supportive partner who understands the demands of a project-driven career, values hard work, and enjoys a well-structured life. I believe in building strong foundations.",
    familySize: "4",
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "423",
    firstName: "Fatima",
    lastName: "Ali",
    gender: "Female",
    dateOfBirth: "1997-05-30",
    country: "India",
    city: "Lucknow",
    height: "160",
    email: "fatima.ali@email.com",
    phone: "9876543278",
    college: "Aligarh Muslim University",
    degree: "B.A. in Islamic Studies",
    income: "650000",
    employmentType: "Government",
    company: "UP Urdu Academy",
    designation: "Librarian",
    maritalStatus: "NeverMarried",
    languages: "Urdu, Hindi, English",
    hobbies: "Reading, Calligraphy, Sufi Music",
    siblings: "1",
    caste: "Syed",
    religion: "Muslim",
    wantKids: "Yes",
    openToRelocate: "No",
    openToPets: "Maybe",
    bio: "Dedicated librarian with a deep appreciation for Islamic literature and culture. I enjoy the intricate art of calligraphy and find solace in Sufi music. Seeking a devout and cultured partner who shares a strong commitment to faith, values intellectual pursuits, and enjoys a peaceful and reflective lifestyle. I believe in the beauty of knowledge and spirituality.",
    familySize: "4",
    importanceOfCasteOfThePartner: "HIGH",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "424",
    firstName: "Raman",
    lastName: "Verma",
    gender: "Male",
    dateOfBirth: "1994-02-09",
    country: "India",
    city: "Delhi",
    height: "176",
    email: "raman.verma@email.com",
    phone: "9876543279",
    college: "IIT Delhi",
    degree: "M.Tech in Artificial Intelligence",
    income: "2000000",
    employmentType: "Private",
    company: "Google India",
    designation: "AI Research Scientist",
    maritalStatus: "NeverMarried",
    languages: "Hindi, English",
    hobbies: "AI Research, Robotics, Trekking",
    siblings: "0",
    caste: "Vaishya",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "No",
    bio: "Cutting-edge AI research scientist fascinated by the potential of artificial intelligence and robotics. When not engrossed in new algorithms, I enjoy challenging myself with treks. Seeking an intellectually brilliant and adventurous partner who shares a passion for innovation, future technologies, and outdoor exploration. I believe in pushing the boundaries of what's possible.",
    familySize: "3",
    importanceOfCasteOfThePartner: "LOW",
    importanceOfReligionOfThePartner: "MEDIUM",
  },
  {
    id: "425",
    firstName: "Sneha",
    lastName: "Gupta",
    gender: "Female",
    dateOfBirth: "1996-08-01",
    country: "India",
    city: "Mumbai",
    height: "162",
    email: "sneha.gupta@email.com",
    phone: "9876543280",
    college: "NMIMS Mumbai",
    degree: "BBA in Marketing",
    income: "900000",
    employmentType: "Private",
    company: "Hindustan Unilever",
    designation: "Assistant Brand Manager",
    maritalStatus: "NeverMarried",
    languages: "Hindi, English, Marathi",
    hobbies: "Marketing Strategy, Social Media, Dancing",
    siblings: "1",
    caste: "Vaishya",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "Yes",
    bio: "Dynamic assistant brand manager passionate about crafting engaging marketing strategies and understanding consumer behavior. I'm active on social media and love to express my vibrant energy through dancing. Seeking an ambitious and supportive partner who appreciates creativity, enjoys a lively social life, and values a blend of professional drive and personal interests. I believe in making an impact.",
    familySize: "4",
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "426",
    firstName: "Aryan",
    lastName: "Sharma",
    gender: "Male",
    dateOfBirth: "1993-10-15",
    country: "India",
    city: "Pune",
    height: "179",
    email: "aryan.sharma@email.com",
    phone: "9876543281",
    college: "Symbiosis Institute of Business Management",
    degree: "MBA in Finance",
    income: "1800000",
    employmentType: "Private",
    company: "JP Morgan Chase",
    designation: "Financial Advisor",
    maritalStatus: "NeverMarried",
    languages: "Hindi, English, Marathi",
    hobbies: "Stock Market, Fitness, Traveling",
    siblings: "0",
    caste: "Brahmin",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Yes",
    openToPets: "No",
    bio: "Astute financial advisor with a deep understanding of the stock market and a commitment to helping clients achieve their financial goals. I maintain a disciplined fitness routine and love traveling to new countries. Seeking an intelligent and driven partner who values financial security, a healthy lifestyle, and exploring diverse cultures. I believe in strategic planning for a prosperous future.",
    familySize: "3",
    importanceOfCasteOfThePartner: "HIGH",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "427",
    firstName: "Priyanka",
    lastName: "Jha",
    gender: "Female",
    dateOfBirth: "1997-04-03",
    country: "India",
    city: "Patna",
    height: "158",
    email: "priyanka.jha@email.com",
    phone: "9876543282",
    college: "Patna University",
    degree: "B.Ed in English",
    income: "680000",
    employmentType: "Government",
    company: "Bihar Education Department",
    designation: "Primary Teacher",
    maritalStatus: "NeverMarried",
    languages: "Hindi, English, Maithili",
    hobbies: "Teaching, Reading, Gardening",
    siblings: "2",
    caste: "Brahmin",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "No",
    openToPets: "Yes",
    bio: "Compassionate primary teacher dedicated to fostering a love for learning in young children. I enjoy reading children's literature, tending to my home garden, and creating a nurturing environment. Seeking a kind and stable partner who values education, family life, and a peaceful existence. I believe in nurturing growth and sowing seeds of knowledge.",
    familySize: "5",
    importanceOfCasteOfThePartner: "HIGH",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "428",
    firstName: "Sunny",
    lastName: "Singh",
    gender: "Male",
    dateOfBirth: "1990-12-25",
    country: "India",
    city: "Chandigarh",
    height: "177",
    email: "sunny.singh@email.com",
    phone: "9876543283",
    college: "Panjab University",
    degree: "B.Tech in Civil Engineering",
    income: "1600000",
    employmentType: "Private",
    company: "Gammon India",
    designation: "Site Engineer",
    maritalStatus: "Divorced",
    languages: "Punjabi, Hindi, English",
    hobbies: "Construction, Gym, Road Trips",
    siblings: "1",
    caste: "Jat",
    religion: "Sikh",
    wantKids: "Maybe",
    openToRelocate: "Yes",
    openToPets: "No",
    bio: "Resilient site engineer with a passion for building robust structures and managing complex projects. I prioritize fitness at the gym and enjoy the freedom of road trips. Looking for an understanding and supportive partner who values honesty, adaptability, and is open to new beginnings. I believe in learning from every experience and building a strong future.",
    familySize: "4",
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "MEDIUM",
  },
  {
    id: "429",
    firstName: "Priya",
    lastName: "Mani",
    gender: "Female",
    dateOfBirth: "1994-06-19",
    country: "India",
    city: "Chennai",
    height: "162",
    email: "priya.mani@email.com",
    phone: "9876543284",
    college: "Anna University",
    degree: "M.Tech in Electronics Engineering",
    income: "1200000",
    employmentType: "Private",
    company: "Intel India",
    designation: "Hardware Design Engineer",
    maritalStatus: "NeverMarried",
    languages: "Tamil, English, Hindi",
    hobbies: "Electronics, Carnatic Music, Coding",
    siblings: "0",
    caste: "Iyengar",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "Maybe",
    openToPets: "No",
    bio: "Dedicated hardware design engineer fascinated by the intricacies of electronics. I find solace and inspiration in Carnatic music and enjoy the logical challenges of coding. Seeking an intellectually curious and culturally appreciative partner who values technical innovation, artistic expression, and a harmonious home life. I believe in precision and passion.",
    familySize: "3",
    importanceOfCasteOfThePartner: "HIGH",
    importanceOfReligionOfThePartner: "HIGH",
  },
  {
    id: "430",
    firstName: "Gautam",
    lastName: "Singh",
    gender: "Male",
    dateOfBirth: "1995-09-07",
    country: "India",
    city: "Varanasi",
    height: "175",
    email: "gautam.singh@email.com",
    phone: "9876543285",
    college: "Banaras Hindu University",
    degree: "B.A. in Philosophy",
    income: "700000",
    employmentType: "Government",
    company: "Ministry of Culture",
    designation: "Cultural Officer",
    maritalStatus: "NeverMarried",
    languages: "Hindi, English, Sanskrit",
    hobbies: "Philosophy, Meditation, Classical Indian Art",
    siblings: "1",
    caste: "Rajput",
    religion: "Hindu",
    wantKids: "Yes",
    openToRelocate: "No",
    openToPets: "Yes",
    bio: "Thoughtful cultural officer with a deep appreciation for philosophy, spiritual reflection, and classical Indian art forms. I practice meditation for inner peace and enjoy exploring ancient wisdom. Seeking a profound and artistically inclined partner who shares a love for intellectual discussions, spiritual growth, and the beauty of Indian heritage. I believe in seeking truth and beauty.",
    familySize: "4",
    importanceOfCasteOfThePartner: "MEDIUM",
    importanceOfReligionOfThePartner: "HIGH",
  },
];

export async function seedCustomers(db: PrismaClient) {
  console.log("🌱 Starting customer seeding...");

  try {
    // Create customers from dummy profiles
    for (const profile of dummyProfiles) {
      await db.customer.create({
        data: {
          userId: "cmenp5rdt0000it83h4dvddsr",
          firstName: profile.firstName,
          lastName: profile.lastName,
          email: profile.email,
          phone: profile.phone,
          dateOfBirth: new Date(profile.dateOfBirth),
          gender: profile.gender as "Male" | "Female",
          country: profile.country,
          city: profile.city,
          height: Number(profile.height),
          college: profile.college,
          degree: profile.degree,
          income: Number(profile.income),
          company: profile.company,
          designation: profile.designation,
          maritalStatus: profile.maritalStatus as "NeverMarried" | "Divorced",
          languages: profile.languages.split(","),
          siblings: Number(profile.siblings),
          caste: profile.caste,
          religion: profile.religion as
            | "No Religion / Atheist"
            | "Hindu"
            | "Muslim"
            | "Sikh"
            | "Christian"
            | "Buddhist"
            | "Jain"
            | "Parsi (Zoroastrian)"
            | "Spiritual (but not religious)",
          wantKids: profile.wantKids as "Yes" | "No" | "Maybe",
          openToRelocate: profile.openToRelocate as "Yes" | "No" | "Maybe",
          openToPets: profile.openToPets as "Yes" | "No" | "Maybe",
          bio: profile.bio,
          familySize: Number(profile.familySize),
          hobbies: profile.hobbies.split(","),
          employmentType: profile.employmentType as "Government" | "Private",
          importanceOfCasteOfThePartner:
            profile.importanceOfCasteOfThePartner as "HIGH" | "MEDIUM" | "LOW",
          importanceOfReligionOfThePartner:
            profile.importanceOfReligionOfThePartner as
              | "HIGH"
              | "MEDIUM"
              | "LOW",
        },
      });

      console.log(
        `✅ Created customer: ${profile.firstName} ${profile.lastName}`,
      );
    }

    console.log(`🎉 Successfully seeded ${dummyProfiles.length} customers!`);

    // Display summary
    const totalCustomers = await db.customer.count();
    console.log(`📊 Total customers in database: ${totalCustomers}`);
  } catch (error) {
    console.error("❌ Error seeding customers:", error);
    throw error;
  }
}
